"""empty message

Revision ID: 11ad8b9f115c
Revises: 
Create Date: 2021-03-08 11:35:19.273631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11ad8b9f115c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('exercisetype', sa.String(length=100), nullable=False),
    sa.Column('reps', sa.String(length=100), nullable=False),
    sa.Column('primarymuscle', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercisesfive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('exercisetype', sa.String(length=100), nullable=False),
    sa.Column('reps', sa.String(length=100), nullable=False),
    sa.Column('primarymuscle', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercisesfour',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('exercisetype', sa.String(length=100), nullable=False),
    sa.Column('reps', sa.String(length=100), nullable=False),
    sa.Column('primarymuscle', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercisesthree',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('exercisetype', sa.String(length=100), nullable=False),
    sa.Column('reps', sa.String(length=100), nullable=False),
    sa.Column('primarymuscle', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercisestwo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('exercisetype', sa.String(length=100), nullable=False),
    sa.Column('reps', sa.String(length=100), nullable=False),
    sa.Column('primarymuscle', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('foods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('primarymacro', sa.String(length=500), nullable=False),
    sa.Column('totalmacros', sa.String(length=100), nullable=False),
    sa.Column('totalcalories', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('foodstwo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('primarymacro', sa.String(length=500), nullable=False),
    sa.Column('totalmacros', sa.String(length=100), nullable=False),
    sa.Column('totalcalories', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('foodstwo')
    op.drop_table('foods')
    op.drop_table('exercisestwo')
    op.drop_table('exercisesthree')
    op.drop_table('exercisesfour')
    op.drop_table('exercisesfive')
    op.drop_table('exercises')
    # ### end Alembic commands ###
